version: 2
updates:
# Update the git submodules
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
  # pull requests
  reviewers:
  - "nirzak"
  labels:
  - "dependencies"
  - "review requested"

# Update the Github Action  versions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - "dependencies"
