[build]
command = "mise install && mise run build -b $DEPLOY_URL"
publish = "public"

[build.environment]
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "mise install && mise run build --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "mise install && mise run build -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' *.github.io *.nirzak.win; script-src 'self' 'unsafe-inline' cdnjs.cloudflare.com www.google-analytics.com *.github.io *.nirzak.win; style-src 'self' 'unsafe-inline' fonts.googleapis.com *.github.io *.nirzak.win; font-src 'self' fonts.gstatic.com;img-src 'self' data:;connect-src 'self' api.github.com;frame-src *.github.io *.nirzak.win;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = '''
            accelerometer=(),
            autoplay=(),
            camera=(),
            encrypted-media=(),
            fullscreen=(*),
            geolocation=(),
            gyroscope=(),
            magnetometer=(),
            microphone=(),
            payment=(*),
            picture-in-picture=(*),
            usb=(),
        '''
